vueuse/motion

docs/installation.md
The npm organization name for nuxt is `nuxtjs`, my first action was to copy the name from the docs and paste in with a yarn add. This actions results in a package not found error, so my suggestion is to use the proper organization name so copy and pasting the package name will result in installing the proper package.
=> docs: fix typo in nuxtjs composition package name

docs/variants.md
Update wording in docs to reflect that a positive 'y' number lowers the element.
So `y: 100` is 100px below 0, `y: -100` is 100px above 0.
=> Update Docs: Positive y lowers element

src/nuxt/module.ts
Nuxt module stopped working after an upgrade to nuxt rc.9, this should fix the issue.
The warning that popped up after upgrade:
``` 
WARN  Module @vueuse/motion is disabled due to incompatibility issues:                                                                                                                                                                                                                                                                                          14:06:27
- [nuxt] Nuxt version `>=3.0.0` is required but currently using `3.0.0-rc.9`
```
Some context: https://github.com/nuxt/framework/issues/7196
=> fix(nuxt): update compatibility field

README.md, docs/content/1.getting-started/1.introduction.md, docs/content/2.features/0.presets.md, docs/content/2.features/1.directive-usage.md, docs/content/2.features/2.composable-usage.md, docs/content/2.features/3.motion-properties.md, docs/content/2.features/4.transition-properties.md, docs/content/2.features/5.variants.md, docs/content/2.features/6.motion-instance.md, docs/content/3.api/1.use-motion.md, docs/content/3.api/10.use-element-transform.md, docs/content/3.api/2.use-spring.md, docs/content/3.api/3.use-motions.md, docs/content/3.api/4.use-motion-properties.md, docs/content/3.api/5.use-motion-variants.md, docs/content/3.api/6.use-motion-transitions.md, docs/content/3.api/7.use-motion-controls.md, docs/content/3.api/9.use-element-style.md
The change to put the following categories to /features/ broke some documentation endpoints:
- Directive Usage
- Composable Usage
- Motion Properties
- Transition Properties
- Variants
- Motion Instance
Just changed the endpoints to /features/{old-endpoint}
Closes #122
=> docs: fix of broken references due to endpoint change

playgrounds/vite/src/demos/Editor.vue, src/components/Motion.ts, src/directive/index.ts, src/features/eventListeners.ts, src/features/lifeCycleHooks.ts, src/features/state.ts, src/features/syncVariants.ts, src/features/visibilityHooks.ts, src/nuxt/module.ts, src/plugin/index.ts, src/presets/fade.ts, src/presets/pop.ts, src/presets/roll.ts, src/presets/slide.ts, src/types/instance.ts, src/types/nuxt.ts, src/types/plugin.ts, src/types/variants.ts, src/useMotion.ts, src/useMotionControls.ts, src/useMotionFeatures.ts, src/useMotionValues.ts, src/useMotionVariants.ts, src/utils/defaults.ts, src/utils/directive.ts, src/utils/is-motion-instance.ts, src/utils/transform-parser.ts
@Tahul 
Adding support for strict typing of the directive keys when creating a motion instance using useMotion and other methods.
I've also added a few other `// @ts-expect-error` that seemed to be missing and caused `tsc` to throw errors. I believe it is cleaner to do it this way rather than do `keyof typeof obj` in every place, since it's something that TypeScript don't intend to change (https://github.com/microsoft/TypeScript/pull/12253#issuecomment-263132208).
=> Add dynamic keys on useMotion directives when calling apply() and other methods

src/nuxt/runtime/templates/motion.d.ts
Once building, there's no type shim generated for the motion plugin file. Here's why we need it:
Nuxt auto-generates types while previewing. In the `.nuxt/types/plugins.d.ts` file, the following type is generated that populated the `NuxtApp` interface:
```typescript
type NuxtAppInjections = 
InjectionType<typeof import("../../../node_modules/@pinia/nuxt/dist/runtime/plugin.vue3").default> &
InjectionType<typeof import("../../../node_modules/nuxt/dist/app/plugins/revive-payload.server").default> &
InjectionType<typeof import("../../../node_modules/nuxt/dist/app/plugins/revive-payload.client").default> &
InjectionType<typeof import("../../../node_modules/nuxt/dist/head/runtime/plugins/unhead").default> &
InjectionType<typeof import("../../../node_modules/nuxt/dist/pages/runtime/plugins/route …
```
=> Add declaration file for motion plugin

docs/content/2.features/1.directive-usage.md
Closes https://github.com/vueuse/motion/issues/124
=> Add short explanations to motion directives

docs/content/1.getting-started/2.nuxt.md, playgrounds/nuxt/nuxt.config.ts, src/nuxt/runtime/templates/motion.ts
Closes #131 
The directives should be defined in `runtimeConfig.public` for client-side to register directives.
=> fix: custom directives in Nuxt (#131)

src/nuxt/runtime/templates/motion.ts
This is a DX improvement when developing - we can avoid loading the entire barrel file at `#app` by using the new granular imports merged in https://github.com/nuxt/nuxt/pull/23951.
=> fix: import nuxt composables from #imports

package.json, pnpm-lock.yaml
This bumps unbuild to v2 to emit `.d.ts` files so users using TypeScript bundler module resolution can get the types for this module.
Without this, the following error (for example) would be printed:
```
components/modal/ModalMediaPreviewCarousel.vue:4:34 - error TS7016: Could not find a declaration file for module '@vueuse/motion'. '/Users/daniel/code/elk-zone/elk/node_modules/.pnpm/@vueuse+motion@2.0.0_rollup@2.79.1_vue@3.3.9/node_modules/@vueuse/motion/dist/index.mjs' implicitly has an 'any' type.
There are types at '/Users/daniel/code/elk-zone/elk/node_modules/@vueuse/motion/dist/index.d.ts', but this result could not be resolved when respecting package.json "exports". The '@vueuse/motion' library may need to update its package.json or typings.
4 import { useReducedMotion } from …
```
=> build: update unbuild and emit `.d.mts` and `.d.cts` as well

package.json
this issue is included in the latest version of Vue & Nuxt.
solved this problem.
=> fix: add types export

src/utils/directive.ts
Close #108 
Makes `visible-once` be abled to resolve.
As for the `@ts-expect-error` comment, I am not sure I should keep that comment ?
Let me know any updates, thank you.
=> fix: support directives kebab-case(#108)

.github/ISSUE_TEMPLATE/bug-report.yml
Adds a template for users reporting bugs, the template is a bit of a mix between the template of Nuxt and Vueuse. This should also add the `pending triage` label to new reported bugs (this label doesn't exist in this repo so this has to be added).
Hopefully this will increase the likelihood of users adding a reproduction to their bug reports.
Tagging for review 
@cpreston321 / @Tahul
=> chore: add bug report issue template

src/directive/index.ts
You may have noticed the [demo page](https://vueuse-motion-demo.netlify.app/) is not working as expected, it seems only the initial motion variant is triggered. While testing #171 in the vite playground I noticed that simply adding en element using a visibility variant would make all motion elements disappear.
Using the Netlify deploy history of the demo page (https://app.netlify.com/sites/vueuse-motion-demo/deploys) I narrowed down when this broke to [this commit](https://github.com/vueuse/motion/commit/1c8d7bb8741cf91910d5ecb8209f07ce68f7cbef). I think that by changing the directive to accept a default value `{}` instead of undefined for variants, the same object is being reused for all `v-motion` usage, essentially each element using `v-motion` is overwriting/merging all the previous …
=> fix: `v-motion` directive variants leaking

playgrounds/vite/src/components/CodeBlock.vue, playgrounds/vite/src/components/DemoBox.vue
Fixes the reset button and code preview for the demo page. When this and #173 are merged the demo page should be fully functional again!
=> docs: fix demo reset and code preview

docs/variants.md
https://stackblitz.com/edit/vue-eeacxc?file=src%2FApp.vue
https://github.com/vueuse/motion/issues/63#issuecomment-1409009281
Elements with `:hovered` variant do not return to `:initial` on mouseleave, on Firefox it works well returning to `:visible`, on Chrome both `:visible` and `:initial` seems to be required.
---
When using `:tapped` without `:hovered`, elements do not return to `:initial` if you click and move the mouse out of the element keeping it clicked.
=> Updating `hovered`, `focused` and `tapped` examples [#63]

docs/installation.md
@vueuse/motion exports has no exported member `directive ` it exports `directive as MotionDirective` instead. 
I stumbled on this while trying to use the motion on component level and using the example from the current docs. 
(using 2.0.0-beta.12)
=> docs: fix MotionDirective import in component level installation example

package.json, scripts/fix-nuxt-build.mjs
Current types are broken:
- motion node cjs
- nuxt types for node and node cjs
This PR also includes an mjs script to fix nuxt in cjs.
https://arethetypeswrong.github.io/?p=%40vueuse%2Fmotion%402.1.0
With this PR (included typesVersions to resolve types for Node):
closes #156
=> fix: types

.github/reproduire/needs-reproduction.md, .github/workflows/reproduire-close.yml, .github/workflows/reproduire.yml
With these actions a comment asking for a reproduction and explaining why _should_ be added automatically whenever the `needs reproduction` label is added, and if the label is not removed within 7 days the issue _should_ get closed automatically and labeled with `closed by bot`. I created an issue on my fork to demonstrate here: https://github.com/BobbieGoede/motion/issues/5.
Often times users open issues without a reproduction and remain unresponsive when asking for a reproduction, or refuse to provide one because it's simple to reproduce in their eyes. This will make checking, asking for reproductions and closing these issues less of a chore (I also think people are less likely to take it personally if it's automated).
I'll be going through the issues to add `needs reproduction` where …
=> chore: add reproduire actions

docs/content/3.api/2.use-spring.md
https://github.com/vueuse/motion/issues/148
The docs for `useSpring` were outdated and the example was not working. I enhanced the useSpring docs by...:
- Replacing the broken example with a new one (resolves #148)
- Fixing the outdated parts in the `useSpring` docs
- Rewriting parts of the `useSpring` docs for better clarity
=> docs: fix useSpring example and rewrite docs

src/features/eventListeners.ts, src/features/lifeCycleHooks.ts
* #63 
Resolves #63 
The event variants use `state` as the variant to return to but the current variant is never set to `initial`, I'm assuming this was done to avoid triggering transitions?
=> fix: return to previous state after hovered event variant

src/components/Motion.ts, src/utils/directive.ts
It looks like the `delay` prop was not applied to variants in the same way as it did for directives, this fixes that. I also refactored the logic slightly to avoid repetition as well as make it more consistent between component and directive, this also acts as preparation to add support for a `duration` prop which will work just like `delay`.
=> fix(component): apply delay to visibility variants

src/directive/index.ts, src/plugin/index.ts
* #74 
Resolves #74 
This changes the way directive presets are handled, the underlying issue is similar to the one solved in https://github.com/vueuse/motion/pull/173, the preset variants are passed and reused and mutated down the line which is most noticeable in situations such as https://github.com/vueuse/motion/issues/74#issuecomment-1721145546.
To prevent this fix from influencing users variants (I suppose there are use cases where mutating a single motion is desired) I tried to only apply this change to directive presets.
=> fix: prevent preset variants from being mutated

docs/components/content/Illustration.vue, docs/components/content/Person.vue, docs/package.json, package.json, playgrounds/nuxt/.npmrc, playgrounds/nuxt/app.vue, playgrounds/nuxt/nuxt.config.ts, playgrounds/nuxt/package.json, playgrounds/vite/src/demos/Editor.vue, pnpm-lock.yaml, src/components/Motion.ts, src/components/MotionGroup.ts, src/components/index.ts, src/motionValue.ts, src/nuxt/module.ts, src/plugin/index.ts, src/types/variants.ts, src/utils/component.ts, src/utils/events.ts, src/utils/transform-parser.ts, tests/components.spec.ts
* #45 
* #186 
This is both the continuation and replacement of #186, after a closer look it appeared that the `<Motion>` component broke by the dependency updates. As mentioned there, these changes resolve #45, and remove a type (`SVGAttributes` in `MotoonProperties` type) of which I'm not sure what the impact is on existing projects.
Since the `<Motion>` component isn't really documented at the moment I figured it would be safe to give it a refactor and see if some changes could be made. I separated its logic and added another component `<MotionGroup>`, this component is used when wanting to apply motion configuration on its child nodes/slots, which I removed from the `<Motion>` component, this makes it possible to no longer require `is` property as well. Please let me know if you have …
=> feat: separate component logic, add `<MotionGroup>` and tests

src/features/eventListeners.ts, src/useMotionControls.ts, src/utils/transition.ts, tests/components.spec.ts, tests/utils/index.ts, tests/utils/intersectionObserver.ts
* #188 
During work on #188 I ran into two issues which made it difficult to test variants using the transition `onComplete` function:
* `onComplete` is called after every variant property animation completion
* When the event variants feature is enabled, variant animations are triggered twice (instantly)
This PR expands on #188 by fixing those issues (so that PR description still applies), I created this separate PR because it touches on more than just the tests.
=> fix: transition `onComplete` triggers after each property animation

docs/components/content/examples/MotionComponent.vue, docs/components/content/examples/MotionGroupComponent.vue, docs/content/2.features/7.components.md, docs/nuxt.config.ts
Adds a very basic page to document the `<Motion>` component, this is essentially a modified version of the "Directive Usage" page. I'm not exactly good at writing documentation so feel free to add more details if necessary. I left out documentation for the `:instance` prop on purpose as this doesn't seem to do anything, this is something to look into later.
@Tahul 
If this documentation is sufficient (for now), I think we should publish a new release 😄
=> docs: add documentation for `<Motion>` component

src/features/eventListeners.ts, tests/components.spec.ts
* #191
Resolves #191
As we are using the [`'mouseout'`](https://developer.mozilla.org/en-US/docs/Web/API/Element/mouseout_event) event to detect whether a motion should leave the hovered state it would also get triggered when hovering a child element.
From what I can tell the [`'mouseleave'`](https://developer.mozilla.org/en-US/docs/Web/API/Element/mouseleave_event) event should be sufficient for this, are there possible use cases for using `'mouseout'`?
I'm not quite sure if the test I added will be stable (not flaky) as it uses timeouts to check if the variant/state remains unchanged, this may need to be improved.
=> fix: leaving hovered state when pointer hovers child element

src/reactiveTransform.ts, src/utils/style.ts, tests/reactiveTransform.spec.ts
* #24 
Resolves #24 
This changes the parsing of `x`, `y` and `z` properties to also allow other units (these are not validated) while keeping the default of transforming plain numbers to `px` units.
=> fix: `x`, `y`, `z` not accepting relative units

src/index.ts, src/nuxt/module.ts
This should fix the components and their types not being registered correctly for Nuxt projects, I suppose this also allows users to use explicit imports for these components if desired.
=> fix: Nuxt component registration

src/components/Motion.ts, src/components/MotionGroup.ts, src/utils/component.ts, tests/components.spec.ts
Motions were not being applied to child nodes of `<MotionGroup>` when used in a for loop, this checks if a child node is a `Fragment` and applies settings to each child node.
=> fix: <MotionGroup> not applying motion to child nodes in v-for

src/nuxt/module.ts
Hi 👋
Currently module options are not public, so `config.public.motion` is always undefined in the Vue plugin.
This PR makes options public.
=> fix(nuxt): merge options with public runtime config

src/utils/component.ts, tests/components.spec.ts
[Issue #202](https://github.com/vueuse/motion/issues/202)
=> fix(component): preserve variant style on rerender

src/useMotionProperties.ts, src/utils/type-feature.ts
same function
https://github.com/vueuse/vueuse/blob/main/packages/shared/utils/index.ts#L115
more information
https://github.com/microsoft/TypeScript/issues/35101
=> fix: add utils for types

docs/components/content/PresetSection.vue
close: #115 
Bind the preview component to the click event.
As for hover, it seems a bit messy to add it, so I haven't added it yet.
=> docs: add click for preset previews

src/types/instance.ts
In line with https://github.com/vuejs/router/pull/2295 and https://github.com/nuxt/nuxt/pull/28542, this moves to augment `vue` rather than `@vue/runtime` core.
This is now officially recommended [in the docs](https://vuejs.org/api/utility-types.html#componentcustomproperties) and it _must_ be done by all libraries or it will break types for _other_ libraries.
=> fix: augment `vue` rather than `@vue/runtime-core`

src/directive/index.ts
Nuxt 3 error with custom directive https://github.com/vueuse/motion/issues/218
Resolves https://github.com/vueuse/motion/issues/218
This changes ensure that the custom directive object are not Vue's reactive object to allow the `StructuredClone` function to as expected.
Perhaps this should have always been included?
=> fix: use `toRaw` when cloning proxy object

src/plugin/index.ts, src/utils/component.ts, src/utils/keys.ts, tests/components.spec.ts
* #201 
Resolves #201 
This changes the Motion components to also use configured custom directives (should we consider renaming this to presets?) and should also allow merging/overriding by passing variant props as you normally do.
Does this make the components feature complete with the directive implementation? If not, let me know what's missing and I'll see to making it work 😄
=> fix: motion component not using and merging custom presets

.github/workflows/ci.yml, .github/workflows/release.yaml, README.md, package.json, pnpm-lock.yaml, scripts/bump-nightly.ts, scripts/release-nightly.sh, scripts/release.sh
* #169 
>[!IMPORTANT]
>These automations require an `NPM_TOKEN` to be set on this repo!
This PR changes the release flow: 
- Each commit on `main` will trigger a release on `@vueuse/motion-nightly`
- Running `pnpm release` will let you pick which version to bump to, this will update the package version and publish a tag with that version. This triggers the `release` action which builds the package and publishes it to npm, adds the changes to `CHANGELOG.md` and a release on the repo.
I have tested these automations on https://github.com/BobbieGoede/motion, though I had to replace the package names temporarily. These automations published https://www.npmjs.com/package/@goede/motion and https://www.npmjs.com/package/@goede/motion-nightly, you can see a release on the repo here …
=> ci: release and nightly release automation

src/plugin/index.ts
Enables autocomplete for MotionPlugin options.
To ensure compatibility, please check that the Vue version in the root codebase matches the Vue version used in the `playground/vite` before testing.
=> fix(types): improve `MotionPlugin` types

src/plugin/index.ts, src/utils/component.ts, vite.config.ts
=> fix: dev environment variable undefined

docs/content/1.getting-started/1.introduction.md, docs/content/3.api/11.reactive-style.md
=> docs: fix `StyleProperties` link and `introduction.md` import

.github/workflows/ci.yml, .github/workflows/nightly-release.yml, .github/workflows/release.yaml, .github/workflows/targets.yml, .prettierrc, build.config.ts, package.json, playgrounds/vite-ssg/vite.config.ts, pnpm-lock.yaml, scripts/fix-nuxt-build.mjs, src/directive/index.ts, src/useMotionControls.ts, src/useMotionVariants.ts, src/useReducedMotion.ts, src/utils/directive.ts, src/utils/transition.ts, tests/components.spec.ts, tsconfig.json
- Drop CJS support (like upcoming version of vueuse)
- Update to latest available vueuse version
- Drop prettier (unused)
=> feat!: drop CJS and use VueUse v13

package.json, pnpm-lock.yaml, src/components/Motion.ts, src/components/MotionGroup.ts, src/nuxt/tsconfig.json, src/plugin/index.ts, src/reactiveStyle.ts, src/reactiveTransform.ts, src/types/variants.ts, src/useElementStyle.ts, src/useElementTransform.ts, src/useMotionProperties.ts, src/utils/component.ts, src/utils/keys.ts, tsconfig.json
The types extending or using `CSSProperties` interface types are somehow being inlined, increasing the build size significantly. For some reason adding type annotations seems to prevent this from happening, it's not pretty but saves a lot of space.
=> fix: externalize `CSSProperties` types

src/nuxt/src/module.ts
Further reduces the build size, the types were being inlined in the nuxt build but we can simply import them from the package, though typescript does complain.
=> fix: nuxt build externalize types

src/types/instance.ts, src/useElementStyle.ts, src/useElementTransform.ts, src/useMotion.ts, src/useMotionControls.ts, src/useMotionProperties.ts, src/useMotionVariants.ts, src/usePermissiveTarget.ts, src/useReducedMotion.ts, src/useSpring.ts, src/utils/element.ts
Prefer importing types and functions from `vue` instead of `@vueuse/` if possible.
=> refactor: import functions and types directly from `vue`
